# Generated by Django 3.2 on 2021-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='is_provincial_capital',
            field=models.BooleanField(blank=True, help_text='If the city is a provincial capital.Takes the Null value if not a municipality.', null=True, verbose_name='Is provincial capital'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='contact_type',
            field=models.CharField(choices=[('ADDRESS', 'Address'), ('EMAIL', 'Email'), ('URL', 'Url'), ('MAIL', 'Snail mail'), ('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('PHONE', 'Telephone'), ('MOBILE', 'Mobile'), ('TEXT', 'Text'), ('VOICE', 'Voice'), ('FAX', 'Fax'), ('CELL', 'Cell'), ('VIDEO', 'Video'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('PAGER', 'Pager'), ('TEXTPHONE', 'Textphone'), ('LINKEDIN', 'LinkedIn')], help_text="A type of medium, e.g. 'fax' or 'email'", max_length=12, verbose_name='type'),
        ),
    ]
