# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='key_events',
            field=models.ManyToManyField(related_name='organization', to='popolo.KeyEvent'),
        ),
    ]
