# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_provincial_capital',
            field=models.NullBooleanField(help_text='If the city is a provincial capital.Takes the Null value if not a municipality.', verbose_name='Is provincial capital'),
        ),
    ]
