# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='identifier',
            field=models.CharField(blank=True, help_text='The main issued identifier, or fiscal code, for organization', max_length=32, null=True, verbose_name='identifier'),
        ),
    ]
