# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='identifier',
            name='source',
            field=models.URLField(blank=True, help_text='The URL of the source where this information comes from', max_length=256, null=True, verbose_name='source'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('name', 'start_date', 'name')]),
        ),
    ]
