# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0002_auto_20171215_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_organization',
            field=models.ForeignKey(blank=True, help_text='The organization who is a member of the organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships_as_member', to='popolo.Organization', verbose_name='Organization'),
        ),
    ]
