# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0002_organization_key_events'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('name', 'identifier', 'start_date')]),
        ),
    ]
