# Generated by Django 3.2 on 2021-04-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0002_auto_20210407_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='appointed_by',
            field=models.ForeignKey(blank=True, help_text='The Membership that officially has appointed this one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointees', to='popolo.membership', verbose_name='Appointed by'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='area',
            field=models.ForeignKey(blank=True, help_text='The geographic area to which the membership is related', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='popolo.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='electoral_event',
            field=models.ForeignKey(blank=True, help_text='The electoral event that assigned this membership', limit_choices_to={'event_type__contains': 'ELE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_assigned', to='popolo.keyevent', verbose_name='Electoral event'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, help_text='The organization on whose behalf the person is a member of the organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_on_behalf_of', to='popolo.organization', verbose_name='On behalf of'),
        ),
    ]
