# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0004_auto_20171207_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='constituency_descr_tmp',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Constituency location description'),
        ),
        migrations.AddField(
            model_name='area',
            name='electoral_list_descr_tmp',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Electoral list description'),
        ),
    ]
