# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0006_auto_20180410_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='electoral_event',
            field=models.ForeignKey(blank=True, help_text='The electoral event that assigned this membership', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships_assigned', to='popolo.ElectoralEvent', verbose_name='Electoral event'),
        ),
        migrations.AlterField(
            model_name='electoralevent',
            name='classification',
            field=models.CharField(choices=[('CAM', 'Camera election'), ('SEN', 'Senato election'), ('EU', 'European election'), ('REG', 'Regional election'), ('PRO', 'Provincial election'), ('COM', 'Municipal election'), ('BY', 'Special election')], help_text='An election classification, e.g. Regional, Municipal', max_length=3, verbose_name='election classification'),
        ),
    ]
