# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0007_auto_20180410_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='thematic_classification',
            field=models.CharField(blank=True, help_text='What the organization does, in what fields, ...', max_length=256, null=True, verbose_name='thematic classification'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='classification',
            field=models.CharField(blank=True, help_text='The nature of the organization, legal form in many cases', max_length=256, null=True, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='othername',
            name='othername_type',
            field=models.CharField(choices=[('FOR', 'Former name'), ('ALT', 'Alternate name'), ('AKA', 'Also Known As'), ('NIC', 'Nickname'), ('ACR', 'Acronym')], default='ALT', help_text='Type of other name, e.g. FOR: former, ALT: alternate, ...', max_length=3, verbose_name='scheme'),
        ),
    ]
