# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0008_auto_20180509_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The profession that contains this', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='popolo.Profession', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(help_text='Profession name', max_length=512, verbose_name='name'),
        ),
    ]
