# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0008_auto_20180926_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='contact_type',
            field=models.CharField(choices=[('ADDRESS', 'Address'), ('EMAIL', 'Email'), ('URL', 'Url'), ('MAIL', 'Snail mail'), ('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('PHONE', 'Telephone'), ('MOBILE', 'Mobile'), ('TEXT', 'Text'), ('VOICE', 'Voice'), ('FAX', 'Fax'), ('CELL', 'Cell'), ('VIDEO', 'Video'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('PAGER', 'Pager'), ('TEXTPHONE', 'Textphone')], help_text="A type of medium, e.g. 'fax' or 'email'", max_length=12, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='identifier',
            field=models.CharField(blank=True, help_text='The main issued identifier, or fiscal code, for organization', max_length=128, null=True, verbose_name='identifier'),
        ),
    ]
