# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0009_auto_20181002_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='note',
            field=models.CharField(blank=True, help_text='A note, e.g. for grouping contact details by physical location', max_length=512, null=True, verbose_name='note'),
        ),
    ]
