# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0010_auto_20180523_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalEducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Education level name', max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Non normalized education level',
                'verbose_name_plural': 'Non normalized education levels',
            },
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='icse_code',
        ),
        migrations.RemoveField(
            model_name='person',
            name='education_level',
        ),
        migrations.AlterField(
            model_name='person',
            name='original_profession',
            field=models.ForeignKey(blank=True, help_text='The profession of this person, non normalized', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_with_this_profession', to='popolo.OriginalProfession', verbose_name='Non normalized profession'),
        ),
        migrations.AddField(
            model_name='originaleducationlevel',
            name='normalized_education_level',
            field=models.ForeignKey(blank=True, help_text='The normalized profession', null=True, on_delete=django.db.models.deletion.CASCADE, to='popolo.EducationLevel'),
        ),
        migrations.AddField(
            model_name='person',
            name='original_education_level',
            field=models.ForeignKey(blank=True, help_text='The education level of this person, non normalized', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_with_this_education_level', to='popolo.OriginalEducationLevel', verbose_name='Non normalized education level'),
        ),
    ]
