# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0011_auto_20181018_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'verbose_name': 'Normalized education level', 'verbose_name_plural': 'Normalized education levels'},
        ),
        migrations.AlterModelOptions(
            name='originaleducationlevel',
            options={'verbose_name': 'Original education level', 'verbose_name_plural': 'Original education levels'},
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='organization',
        ),
        migrations.AddField(
            model_name='ownership',
            name='owned_organization',
            field=models.ForeignKey(default=None, help_text='The owned organization', on_delete=django.db.models.deletion.CASCADE, related_name='ownerships_as_owned', to='popolo.Organization', verbose_name='Owned organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownership',
            name='owner_organization',
            field=models.ForeignKey(blank=True, help_text='An organization owning part of this organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships_as_owner', to='popolo.Organization', verbose_name='Owning organization'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='owner_person',
            field=models.ForeignKey(blank=True, help_text='A person owning part of this organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='popolo.Person', verbose_name='Person'),
        ),
    ]
