# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-31 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0012_auto_20181229_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner_organization',
            field=models.ForeignKey(blank=True, help_text='An organization owning part of this organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='popolo.Organization', verbose_name='Owning organization'),
        ),
    ]
