# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0012_auto_20180524_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='name',
            field=models.CharField(help_text='Education level name', max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='originaleducationlevel',
            name='name',
            field=models.CharField(help_text='Education level name', max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='originalprofession',
            name='name',
            field=models.CharField(help_text='The original profession name', max_length=512, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(help_text='Normalized profession name', max_length=512, unique=True, verbose_name='name'),
        ),
    ]
