# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0013_auto_20180525_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='A label describing the post', max_length=256, verbose_name='label')),
                ('other_label', models.CharField(blank=True, help_text='An alternate label, such as an abbreviation', max_length=32, null=True, verbose_name='other label')),
                ('priority', models.IntegerField(blank=True, help_text='The priority of this role type, within the same classification group', null=True, verbose_name='priority')),
                ('classification', models.ForeignKey(help_text='The OP_FORMA_GIURIDICA classification this role type is related to', on_delete=django.db.models.deletion.CASCADE, related_name='role_types', to='popolo.Classification')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='organizations',
            field=models.ManyToManyField(related_name='posts_available', through='popolo.Membership', to='popolo.Organization'),
        ),
        migrations.AlterField(
            model_name='post',
            name='holders',
            field=models.ManyToManyField(related_name='roles_held', through='popolo.Membership', to='popolo.Person'),
        ),
    ]
