# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-02 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0013_auto_20181231_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_identity_verified',
            field=models.BooleanField(default=False, help_text='If tax_id was verified formally', verbose_name='identity verified'),
        ),
    ]
