# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0014_auto_20180603_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='role_type',
            field=models.ForeignKey(blank=True, help_text='The structured role type for this post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='popolo.RoleType', verbose_name='Role type'),
        ),
    ]
