# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0014_person_is_identity_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(blank=True, help_text='A label describing the post', max_length=512, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='label',
            field=models.CharField(help_text='A label describing the post, better keep it unique and put the classification descr into it', max_length=256, verbose_name='label'),
        ),
    ]
