# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0015_post_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.FloatField(blank=True, help_text='The absolute priority of this specific post, with respect to all others.', null=True, verbose_name='priority'),
        ),
    ]
