# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0016_post_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roletype',
            options={'verbose_name': 'Role type', 'verbose_name_plural': 'Role types'},
        ),
        migrations.AlterField(
            model_name='originaleducationlevel',
            name='normalized_education_level',
            field=models.ForeignKey(blank=True, help_text='The normalized education_level', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_education_levels', to='popolo.EducationLevel'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='label',
            field=models.CharField(help_text='A label describing the post', max_length=256, verbose_name='label'),
        ),
        migrations.AlterUniqueTogether(
            name='roletype',
            unique_together=set([('classification', 'label')]),
        ),
    ]
