# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0017_auto_20180606_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoralevent',
            name='electoral_system',
            field=models.CharField(blank=True, help_text='The electoral system under which this election session is held', max_length=255, null=True, verbose_name='electoral system'),
        ),
        migrations.AlterUniqueTogether(
            name='electoralevent',
            unique_together=set([('start_date', 'classification')]),
        ),
    ]
