# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0018_auto_20180611_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoralevent',
            name='classification',
            field=models.CharField(choices=[('CAM', 'Camera election'), ('SEN', 'Senato election'), ('EU', 'European election'), ('REG', 'Regional election'), ('PRO', 'Provincial election'), ('MET', 'Metropolitan election'), ('COM', 'Municipal election'), ('BY', 'Special election')], help_text='An election classification, e.g. Regional, Municipal', max_length=3, verbose_name='election classification'),
        ),
        migrations.AlterField(
            model_name='electoralevent',
            name='event_type',
            field=models.CharField(choices=[('SIN', 'Single round'), ('1ST', 'First round'), ('BAL', 'Run-off election'), ('2LV', 'Second level election')], default='SIN', help_text='The electoral event type, e.g.: First round, run-off', max_length=3, verbose_name='event type'),
        ),
    ]
