# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0019_auto_20180625_2213'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='identifier',
            index=models.Index(fields=['identifier'], name='popolo_iden_identif_ace930_idx'),
        ),
    ]
