# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0020_auto_20180627_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='area',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='arearelationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='arearelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='electoralevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='electoralevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='electoralresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='electoralresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='personalrelationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='personalrelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
    ]
