# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0021_auto_20180628_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='constituency_descr_tmp',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Constituency location description'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='electoral_list_descr_tmp',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Electoral list description'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, db_index=True, help_text='A gender', max_length=32, null=True, verbose_name='gender'),
        ),
    ]
