# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0021_auto_20190724_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electoralresult',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='event',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='list',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='organization',
        ),
        migrations.DeleteModel(
            name='ElectoralResult',
        ),
    ]
