# Generated by Django 2.2.8 on 2019-12-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0022_auto_20191112_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrelationship',
            name='classification',
            field=models.ForeignKey(help_text='The classification for this organization relationship', limit_choices_to={'scheme': 'OP_TIPO_RELAZIONE_ORG'}, on_delete=django.db.models.deletion.CASCADE, related_name='organization_relationships', to='popolo.Classification'),
        ),
        migrations.AlterField(
            model_name='personalrelationship',
            name='classification',
            field=models.ForeignKey(help_text='The classification for this personal relationship', limit_choices_to={'scheme': 'OP_TIPO_RELAZIONE_PERS'}, on_delete=django.db.models.deletion.CASCADE, related_name='personal_relationships', to='popolo.Classification'),
        ),
    ]
