# Generated by Django 2.2.9 on 2020-01-23 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0024_auto_20200116_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='electoralresult',
            name='second_round',
            field=models.OneToOneField(blank=True, help_text='Some may require a second round.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_round', to='popolo.ElectoralResult', verbose_name='second round electoral result'),
        ),
        migrations.AlterUniqueTogether(
            name='electoralresult',
            unique_together={('electoral_event', 'institution', 'second_round')},
        ),
    ]
