# Generated by Django 2.2.9 on 2019-12-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0024_coalitionelectoralresult_electoralendorsement_electoralresult_listelectoralresult_tmpcoalitionelecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='listelectoralresult',
            name='seats',
            field=models.PositiveIntegerField(blank=True, help_text='The number of seats won by the list', null=True, verbose_name='number of seats won'),
        ),
    ]
