# Generated by Django 2.2.10 on 2020-02-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0025_auto_20200123_0301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electoralresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='electoral_event',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='second_round',
        ),
        migrations.RemoveField(
            model_name='listelectoralresult',
            name='coalition_result',
        ),
        migrations.RemoveField(
            model_name='listelectoralresult',
            name='electoral_result',
        ),
        migrations.DeleteModel(
            name='CoalitionElectoralResult',
        ),
        migrations.DeleteModel(
            name='ElectoralResult',
        ),
        migrations.DeleteModel(
            name='ListElectoralResult',
        ),
    ]
