# Generated by Django 2.2.9 on 2020-01-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0025_listelectoralresult_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electoralendorsement',
            name='electoral_list',
        ),
        migrations.RemoveField(
            model_name='electoralendorsement',
            name='event',
        ),
        migrations.RemoveField(
            model_name='electoralendorsement',
            name='party',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='electoral_event',
        ),
        migrations.RemoveField(
            model_name='listelectoralresult',
            name='coalition_result',
        ),
        migrations.RemoveField(
            model_name='listelectoralresult',
            name='electoral_list',
        ),
        migrations.RemoveField(
            model_name='listelectoralresult',
            name='electoral_result',
        ),
        migrations.RemoveField(
            model_name='tmpcoalitionelectoralresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tmpelectoralresult',
            name='id',
        ),
        migrations.DeleteModel(
            name='CoalitionElectoralResult',
        ),
        migrations.DeleteModel(
            name='ElectoralEndorsement',
        ),
        migrations.DeleteModel(
            name='ElectoralResult',
        ),
        migrations.DeleteModel(
            name='ListElectoralResult',
        ),
        migrations.DeleteModel(
            name='TmpCoalitionElectoralResult',
        ),
        migrations.DeleteModel(
            name='TmpElectoralResult',
        ),
    ]
