# Generated by Django 2.2.10 on 2020-02-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0026_auto_20200217_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoalitionElectoralResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(help_text='The number of votes received by the coalition', verbose_name='number of votes')),
                ('seats', models.PositiveIntegerField(blank=True, help_text='The number of seats won by the coalition', null=True, verbose_name='number of seats won')),
                ('tmp_candidate', models.CharField(blank=True, help_text="The full name of a candidate, to be used as a temporary placeholder when it's not possible to get or create a full person object", max_length=96, null=True, verbose_name='candidate full name (placeholder)')),
                ('candidate', models.ForeignKey(blank=True, help_text='The leader of the coalition', null=True, on_delete=django.db.models.deletion.CASCADE, to='popolo.Person', verbose_name='coalition leader')),
            ],
            options={
                'verbose_name': 'coalition electoral result',
                'verbose_name_plural': 'coalition electoral results',
            },
        ),
        migrations.CreateModel(
            name='ElectoralOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of an electoral organization', max_length=96, verbose_name='full name')),
                ('electoral_event', models.ForeignKey(help_text='The electoral event', on_delete=django.db.models.deletion.CASCADE, related_name='electoral_organizations', to='popolo.KeyEvent', verbose_name='electoral event')),
                ('parent', models.ForeignKey(blank=True, help_text='The electoral organization this organization is part of (e.g. the coalition)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='popolo.ElectoralOrganization', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'electoral organization',
                'verbose_name_plural': 'electoral organization',
                'ordering': ('electoral_event', 'name', 'parent'),
                'unique_together': {('name', 'electoral_event')},
            },
        ),
        migrations.CreateModel(
            name='ElectoralResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_voters', models.PositiveIntegerField(blank=True, help_text='The number of people who were eligible to cast a vote (e.g. the size of the electorate)', null=True, verbose_name='registered voters')),
                ('votes_cast', models.PositiveIntegerField(help_text='The number of votes cast (e.g. the absolute turnout of the election; the total number of voters who cast a vote in this electoral event)', verbose_name='number of votes cast')),
                ('invalid_votes', models.PositiveIntegerField(blank=True, default=0, help_text='The number of blank, null, spoiled, or "none of the above" votes, if any. Defaults to zero.', null=True, verbose_name='number of invalid votes cast')),
                ('blank_votes', models.PositiveIntegerField(blank=True, help_text="The number of blank electoral votes, to be used when the value is available. Sometimes the number of blank votes is not available as a standalone value, but it's instead included in the total number of invalid votes, so it cannot be determined. ", null=True, verbose_name='number of blank votes')),
                ('lists_votes', models.PositiveIntegerField(blank=True, help_text='Some elections allow to vote for just a candidate while not marking any list. This is the number of voters who explicitly marked a list.Since the value is not always available or allowed, this is a situational field.', null=True, verbose_name='number of lists votes')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether the election result is considered valid or not (e.g. when quorum is not reached, the election is not valid). Defaults to `True`.', verbose_name='whether the election result is valid')),
                ('constituency', models.ForeignKey(help_text='The official area of a country that elects a representative (as to a legislative or executive position).(e.g. an electoral district).', on_delete=django.db.models.deletion.CASCADE, related_name='electoral_results', to='popolo.Area', verbose_name='constituency')),
                ('electoral_event', models.ForeignKey(help_text='The electoral event result', on_delete=django.db.models.deletion.CASCADE, related_name='electoral_results', to='popolo.KeyEvent', verbose_name='electoral event')),
                ('institution', models.ForeignKey(help_text='The formal organization this electoral result refers to', on_delete=django.db.models.deletion.CASCADE, related_name='electoral_results', to='popolo.Organization', verbose_name='institution')),
                ('second_round', models.OneToOneField(blank=True, help_text='Some may require a second round.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_round', to='popolo.ElectoralResult', verbose_name='second round electoral result')),
            ],
            options={
                'verbose_name': 'electoral result',
                'verbose_name_plural': 'electoral results',
                'unique_together': {('electoral_event', 'institution', 'second_round')},
            },
        ),
        migrations.CreateModel(
            name='ListElectoralResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp_electoral_list', models.CharField(help_text='The full name of an electoral list (placeholder)', max_length=96, verbose_name='electoral list name (placeholder)')),
                ('votes', models.PositiveIntegerField(blank=True, help_text='The number of votes received by the electoral list', null=True, verbose_name='number of votes')),
                ('seats', models.PositiveIntegerField(blank=True, help_text='The number of seats won by the list', null=True, verbose_name='number of seats won')),
                ('coalition_result', models.ForeignKey(help_text='The result of the coalition of which this electoral list is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='list_electoral_results', to='popolo.CoalitionElectoralResult', verbose_name='coalition electoral result')),
                ('electoral_list', models.ForeignKey(help_text='The electoral list', on_delete=django.db.models.deletion.CASCADE, related_name='list_electoral_results', to='popolo.ElectoralOrganization', verbose_name='electoral list')),
                ('electoral_result', models.ForeignKey(help_text='The general electoral result', on_delete=django.db.models.deletion.CASCADE, related_name='list_electoral_results', to='popolo.ElectoralResult', verbose_name='general electoral result')),
            ],
            options={
                'verbose_name': 'list electoral result',
                'verbose_name_plural': 'list electoral results',
            },
        ),
        migrations.AddField(
            model_name='coalitionelectoralresult',
            name='electoral_coalition',
            field=models.ForeignKey(help_text='The electoral coalition', on_delete=django.db.models.deletion.CASCADE, related_name='coalition_electoral_results', to='popolo.ElectoralOrganization', verbose_name='electoral coalition'),
        ),
        migrations.AddField(
            model_name='coalitionelectoralresult',
            name='electoral_result',
            field=models.ForeignKey(help_text='The general electoral result', on_delete=django.db.models.deletion.CASCADE, related_name='coalition_electoral_results', to='popolo.ElectoralResult', verbose_name='general electoral result'),
        ),
    ]
