# Generated by Django 2.2.9 on 2020-01-07 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0026_auto_20200107_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoalitionElectoralResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(help_text='The number of votes received by the coalition', verbose_name='number of votes')),
                ('seats', models.PositiveIntegerField(blank=True, help_text='The number of seats won by the coalition', null=True, verbose_name='number of seats won')),
                ('candidate', models.ForeignKey(blank=True, help_text='The leader of the coalition', null=True, on_delete=django.db.models.deletion.CASCADE, to='popolo.Person', verbose_name='coalition leader')),
            ],
            options={
                'verbose_name': 'coalition electoral result',
                'verbose_name_plural': 'coalition electoral results',
            },
        ),
        migrations.CreateModel(
            name='ElectoralResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_voters', models.PositiveIntegerField(blank=True, help_text='The number of people who were eligible to cast a vote (e.g. the size of the electorate)', null=True, verbose_name='registered voters')),
                ('votes_cast', models.PositiveIntegerField(help_text='The number of votes cast (e.g. the absolute turnout of the election; the total number of voters who cast a vote in this electoral event)', verbose_name='number of votes cast')),
                ('invalid_votes', models.PositiveIntegerField(blank=True, default=0, help_text='The number of blank, null, spoiled, or "none of the above" votes, if any. Defaults to zero.', null=True, verbose_name='number of invalid votes cast')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether the election result is considered valid or not (e.g. when quorum is not reached, the election is not valid). Defaults to `True`.', verbose_name='whether the election result is valid')),
                ('electoral_event', models.ForeignKey(help_text='The electoral event result', on_delete=django.db.models.deletion.CASCADE, related_name='electoral_result', to='popolo.KeyEvent', verbose_name='electoral event')),
                ('institution', models.ForeignKey(help_text='The formal organization this election refers to', on_delete=django.db.models.deletion.CASCADE, related_name='electoral_result', to='popolo.Organization', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'electoral result',
                'verbose_name_plural': 'electoral results',
                'unique_together': {('electoral_event', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='TmpCoalitionElectoralResult',
            fields=[
                ('candidate', models.CharField(blank=True, help_text="The full name of a candidate, to be used as a temporary placeholder when it's not possible to get or create a full person object", max_length=96, null=True, verbose_name='candidate full name')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tmp', serialize=False, to='popolo.CoalitionElectoralResult')),
            ],
        ),
        migrations.CreateModel(
            name='TmpElectoralResult',
            fields=[
                ('blank_votes', models.PositiveIntegerField(blank=True, help_text="The number of blank electoral votes, to be used when the value is available. Sometimes the number of blank votes is not available as a standalone value, but it's instead included in the total number of invalid votes, so it cannot be determined.", null=True, verbose_name='number of blank votes')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tmp', serialize=False, to='popolo.ElectoralResult')),
            ],
        ),
        migrations.CreateModel(
            name='ListElectoralResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(blank=True, help_text='The number of votes received by the electoral list', null=True, verbose_name='number of votes')),
                ('seats', models.PositiveIntegerField(blank=True, help_text='The number of seats won by the list', null=True, verbose_name='number of seats won')),
                ('coalition_result', models.ForeignKey(help_text='The result of the coalition of which this electoral list is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='lists_electoral_results', to='popolo.CoalitionElectoralResult', verbose_name='coalition electoral result')),
                ('electoral_list', models.ForeignKey(help_text='The electoral list', on_delete=django.db.models.deletion.CASCADE, related_name='lists_electoral_results', to='popolo.Organization', verbose_name='electoral list')),
                ('electoral_result', models.ForeignKey(help_text='The general electoral result', on_delete=django.db.models.deletion.CASCADE, related_name='lists_electoral_results', to='popolo.ElectoralResult', verbose_name='general electoral result')),
            ],
            options={
                'verbose_name': 'list electoral result',
                'verbose_name_plural': 'list electoral results',
            },
        ),
        migrations.CreateModel(
            name='ElectoralEndorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electoral_list', models.ForeignKey(help_text='The endorsed electoral list', on_delete=django.db.models.deletion.CASCADE, related_name='endorsed_by', to='popolo.Organization', verbose_name='endorsed electoral list')),
                ('event', models.ForeignKey(help_text='The electoral event', on_delete=django.db.models.deletion.CASCADE, to='popolo.KeyEvent', verbose_name='electoral event')),
                ('party', models.ForeignKey(help_text='The endorsing party', on_delete=django.db.models.deletion.CASCADE, related_name='endorsed', to='popolo.Organization', verbose_name='endorsing political party')),
            ],
            options={
                'verbose_name': 'electoral endorsment',
                'verbose_name_plural': 'electoral endorsements',
            },
        ),
    ]
