# Generated by Django 2.2.9 on 2020-02-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0027_auto_20200217_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electoralorganization',
            options={'ordering': ('electoral_event', 'name'), 'verbose_name': 'electoral organization', 'verbose_name_plural': 'electoral organization'},
        ),
    ]
