# Generated by Django 2.2.11 on 2020-04-21 05:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0028_auto_20200218_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='The geometry of the area', null=True, srid=4326, verbose_name='Geometry'),
        ),
    ]
