# Generated by Django 2.2.13 on 2020-09-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0029_auto_20200421_0736'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electoralorganization',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='electoralorganization',
            name='electoral_event',
        ),
        migrations.RemoveField(
            model_name='electoralorganization',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='electoralresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='electoral_event',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='electoralresult',
            name='second_round',
        ),
        migrations.RemoveField(
            model_name='listelectoralresult',
            name='coalition_result',
        ),
        migrations.RemoveField(
            model_name='listelectoralresult',
            name='electoral_list',
        ),
        migrations.RemoveField(
            model_name='listelectoralresult',
            name='electoral_result',
        ),
        migrations.DeleteModel(
            name='CoalitionElectoralResult',
        ),
        migrations.DeleteModel(
            name='ElectoralOrganization',
        ),
        migrations.DeleteModel(
            name='ElectoralResult',
        ),
        migrations.DeleteModel(
            name='ListElectoralResult',
        ),
    ]
